import {z} from 'zod'; const id=z.string().uuid(); const optionalText=n=>z.string().trim().max(n).optional().nullable();
export const authRegister=z.object({body:z.object({name:z.string().trim().min(2).max(80),email:z.string().email().max(254),password:z.string().min(8).max(128)}),query:z.any(),params:z.any()});
export const authLogin=z.object({body:z.object({email:z.string().email(),password:z.string().min(1).max(128)}),query:z.any(),params:z.any()});
export const task=z.object({body:z.object({title:z.string().trim().min(1).max(160),description:optionalText(2000),priority:z.enum(['low','medium','high','urgent']).default('medium'),status:z.enum(['pending','in_progress','completed']).default('pending'),due_date:z.string().date().optional().nullable(),category:optionalText(60)}),query:z.any(),params:z.any()});
export const expense=z.object({body:z.object({amount:z.coerce.number().positive().max(10000000),category_id:id,description:optionalText(500),expense_date:z.string().date(),payment_method:z.enum(['Cash','UPI','Card','Bank Transfer','Other']).default('UPI'),is_recurring:z.boolean().default(false)}),query:z.any(),params:z.any()});
export const category=z.object({body:z.object({name:z.string().trim().min(1).max(60),color:z.string().regex(/^#[0-9A-Fa-f]{6}$/).default('#6366f1')}),query:z.any(),params:z.any()});
export const budget=z.object({body:z.object({category_id:id.optional().nullable(),amount:z.coerce.number().positive(),month:z.coerce.number().int().min(1).max(12),year:z.coerce.number().int().min(2020).max(2100)}),query:z.any(),params:z.any()});
export const saving=z.object({body:z.object({name:z.string().trim().min(1).max(100),target_amount:z.coerce.number().positive(),current_amount:z.coerce.number().min(0).default(0),target_date:z.string().date().optional().nullable()}),query:z.any(),params:z.any()});
export const taskStatus=z.object({body:z.object({status:z.enum(['pending','in_progress','completed'])}),query:z.any(),params:z.any()});
