create extension if not exists "pgcrypto";
create table public.users (id uuid primary key default gen_random_uuid(),name text not null,email text not null unique,password_hash text not null,avatar_url text,currency text not null default 'INR',monthly_budget numeric(12,2) not null default 0 check(monthly_budget>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,title text not null,description text,priority text not null default 'medium' check(priority in ('low','medium','high','urgent')),status text not null default 'pending' check(status in ('pending','in_progress','completed')),due_date date,category text,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.expense_categories (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,name text not null,color text not null default '#6366f1',created_at timestamptz not null default now(),unique(user_id,name));
create table public.expenses (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,category_id uuid not null references public.expense_categories(id) on delete restrict,amount numeric(12,2) not null check(amount>0),description text,expense_date date not null,payment_method text not null default 'UPI' check(payment_method in ('Cash','UPI','Card','Bank Transfer','Other')),is_recurring boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.budgets (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,category_id uuid references public.expense_categories(id) on delete cascade,amount numeric(12,2) not null check(amount>0),month int not null check(month between 1 and 12),year int not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique nulls not distinct(user_id,category_id,month,year));
create table public.savings_goals (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.users(id) on delete cascade,name text not null,target_amount numeric(12,2) not null check(target_amount>0),current_amount numeric(12,2) not null default 0 check(current_amount>=0),target_date date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index tasks_user_due_idx on public.tasks(user_id,due_date);create index expenses_user_date_idx on public.expenses(user_id,expense_date);create index budgets_user_period_idx on public.budgets(user_id,year,month);
-- API uses the server-only service role and enforces ownership in every query. Enable RLS as defence in depth for any future direct client access.
alter table public.users enable row level security;alter table public.tasks enable row level security;alter table public.expense_categories enable row level security;alter table public.expenses enable row level security;alter table public.budgets enable row level security;alter table public.savings_goals enable row level security;
